---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stormforge
  namespace: stormforge-system
spec:
  interval: 10m
  releaseName: stormforge-agent
  chartRef:
    kind: OCIRepository
    name: stormforge-charts
    namespace: flux-system
#  targetNamespace: stormforge-system
#  valuesFrom:
#  - kind: Secret
#    name: aws-secret
#    valuesKey: stormforge-secret
#    targetPath: stormforgeToken
