---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stormforge
  namespace: stormforge-system
spec:
  chart:
    spec:
      chart: stormforge-agent
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: OCIRepository
        name: stormforge-charts
        namespace: flux-system
      version: 2.14.0
  interval: 1m0s
  targetNamespace: stormforge-system
  valuesFrom:
  - kind: Secret
    name: aws-secret
    valuesKey: stormforge-secret
    targetPath: stormforgeToken
